Initial working ServiceEndpointsTest.
Sadly, this did not actually detect the error that motivated me to write
the test. I saw this when I tried to use ServiceEndpoints:

java.lang.IllegalStateException: getInputStream() has already been called for this request
	at org.apache.catalina.connector.Request.getReader(Request.java:1134)
	at org.apache.catalina.connector.RequestFacade.getReader(RequestFacade.java:392)
	at works.bosk.spring.boot.ServiceEndpoints.putAny(ServiceEndpoints.java:68)

Apparently, the Spring Boot environment set up by AutoConfigureMockMvc
isn't close enough to a real production usage to reproduce this problem.

Regardless, setting up these kinds of tests is tricky so it's nice to
have this code committed.

Also, I think I've improved the ServiceEndpoints to make them a bit more
idomatic, and also forgiving (eg. they can handle "/bosk" as well as "/bosk/").